engines:
  rubocop:
    enabled: true
    #checks:
    # Rubocop/Metrics/ClassLength:
    #   enabled: false
  brakeman:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
ratings:
  paths:
  - src/lib/**
  - src/clients/**
  - "**.rb"
exclude_paths:
- spec/**/*
